apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
  namespace: default
  labels:
    app: traefik
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: traefik
        name: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:1.7.9
          name: traefik
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: dashboard
              containerPort: 8080
              protocol: TCP
          args:
            - --configfile=/config/traefik.toml
          volumeMounts:
          - mountPath: /config
            name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: traefik
        name: config