apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost